WebApplication1/Pages/Courses/Assignments/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using WebApplication1.Data;
using WebApplication1.Models;

namespace WebApplication1.Pages.Courses.Assignments
{
    public class CreateModel : PageModel
    {
        private readonly WebApplication1.Data.ApplicationDbContext _context;

        public CreateModel(WebApplication1.Data.ApplicationDbContext context)
        {
            _context = context;
        }

		public List<string> TypeOptions { get; set; } = new List<string> { "Assignment", "Exam", "Project", "Quiz" };
        public int CourseId { get; set; }

		public IActionResult OnGet(int courseId)
        {
            this.CourseId = courseId;
			ViewData["StudentId"] = new SelectList(_context.Students, "Id", "LastName");
            return Page();
        }

        [BindProperty]
        public Assignment Assignment { get; set; } = default!;

        // For more information, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync(int courseId)
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

			Assignment.CourseId = courseId;
			_context.Assignments.Add(Assignment);
            await _context.SaveChangesAsync();

            return RedirectToPage($"/Courses/Assignments/Index", new { courseId });
        }
    }
}

WebApplication1/Pages/Courses/Assignments/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Data;
using WebApplication1.Models;

namespace WebApplication1.Pages.Courses.Assignments
{
    public class DeleteModel : PageModel
    {
        private readonly WebApplication1.Data.ApplicationDbContext _context;

        public DeleteModel(WebApplication1.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Assignment Score { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var score = await _context.Assignments.Include(c => c.Course).FirstOrDefaultAsync(m => m.Id == id);

            if (score == null)
            {
                return NotFound();
            }
            else
            {
                Score = score;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var score = await _context.Assignments.FindAsync(id);
            if (score != null)
            {
                Score = score;
                _context.Assignments.Remove(Score);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

WebApplication1/Pages/Courses/Assignments/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Data;
using WebApplication1.Models;

namespace WebApplication1.Pages.Courses.Assignments
{
    public class DetailsModel : PageModel
    {
        private readonly WebApplication1.Data.ApplicationDbContext _context;

        public DetailsModel(WebApplication1.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public Assignment Assignment { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var assignment = await _context.Assignments.FirstOrDefaultAsync(m => m.Id == id);
            if (assignment == null)
            {
                return NotFound();
            }
            else
            {
				Assignment = assignment;
            }
            return Page();
        }
    }
}

WebApplication1/Pages/Courses/Assignments/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Data;
using WebApplication1.Models;

namespace WebApplication1.Pages.Courses.Assignments
{
    public class EditModel : PageModel
    {
        private readonly WebApplication1.Data.ApplicationDbContext _context;

        public EditModel(WebApplication1.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Assignment Assignment { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var assignment =  await _context.Assignments.FirstOrDefaultAsync(m => m.Id == id);
            if (assignment == null)
            {
                return NotFound();
            }
			Assignment = assignment;
           ViewData["CourseId"] = new SelectList(_context.Courses, "Id", "Name");
           ViewData["StudentId"] = new SelectList(_context.Students, "Id", "Id");
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more information, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Assignment).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ScoreExists(Assignment.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool ScoreExists(int id)
        {
            return _context.Assignments.Any(e => e.Id == id);
        }
    }
}

WebApplication1/Pages/Courses/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using WebApplication1.Data;
using WebApplication1.Models;

namespace WebApplication1.Pages.Courses
{
    public class CreateModel : PageModel
    {
        private readonly WebApplication1.Data.ApplicationDbContext _context;

        public CreateModel(WebApplication1.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            ViewData["TeacherId"] = new SelectList(_context.Teachers, "Id", "LastName", null);
            return Page();
        }

        [BindProperty]
        public Course Course { get; set; } = default!;

        // For more information, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Courses.Add(Course);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

WebApplication1/Pages/Courses/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Data;
using WebApplication1.Models;

namespace WebApplication1.Pages.Courses
{
    public class DeleteModel : PageModel
    {
        private readonly WebApplication1.Data.ApplicationDbContext _context;

        public DeleteModel(WebApplication1.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Course Course { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Courses.Include(c => c.Teacher).FirstOrDefaultAsync(m => m.Id == id);

            if (course == null)
            {
                return NotFound();
            }
            else
            {
                Course = course;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Courses.FindAsync(id);
            if (course != null)
            {
                Course = course;
                _context.Courses.Remove(Course);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

WebApplication1/Pages/Courses/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Data;
using WebApplication1.Models;

namespace WebApplication1.Pages.Courses
{
    public class DetailsModel : PageModel
    {
        private readonly WebApplication1.Data.ApplicationDbContext _context;

        public DetailsModel(WebApplication1.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public Course Course { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Course = await _context.Courses // FIX: Use _context.Courses instead of _context.Course
                .Include(c => c.Teacher)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (Course == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

WebApplication1/Pages/Students/Dashboard.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Data;
using WebApplication1.Models;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using System.IO;

namespace WebApplication1.Pages.Students
{
    public class DashboardModel : PageModel
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public DashboardModel(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public List<Course> EnrolledCourses { get; set; } = new();
        public List<Teacher> CurrentTeachers { get; set; } = new();
        public Dictionary<int, string> CourseGrades { get; set; } = new();
        public Dictionary<int, List<AssignmentInfo>> AssignmentsByCourse { get; set; } = new();
        public Dictionary<int, string> CourseNames { get; set; } = new();
        public string StudentFirstName { get; set; } = "";
        public int StudentId { get; set; }
        public byte[]? StudentProfilePicture { get; set; }
        public string? StudentProfilePictureContentType { get; set; }
        public string CurrentQuarterName { get; set; } = "";
        public int CurrentQuarterYear { get; set; }

        public class AssignmentInfo
        {
            public string Title { get; set; } = "";
            public DateTime? DueDate { get; set; }
            public int PointsPossible { get; set; }
            public int PointsEarned { get; set; }
            public string Grade { get; set; } = "-";
        }

        public async Task<IActionResult> OnGetAsync(int studentId)
        {
            // Get the student and set the first name
            var student = await _context.Students
                .AsNoTracking()
                .FirstOrDefaultAsync(s => s.Id == studentId);

            if (student == null)
            {
                return NotFound();
            }

            // Get the logged-in user's email
            var userEmail = User.Identity?.IsAuthenticated == true
                ? User.FindFirstValue(ClaimTypes.Email)
                : null;

            // Only allow access if the logged-in user's email matches the student's email
            if (string.IsNullOrEmpty(userEmail) || !string.Equals(userEmail, student.Email, StringComparison.OrdinalIgnoreCase))
            {
                return Forbid();
            }

            StudentId = studentId;
            StudentFirstName = student.FirstName;
            StudentProfilePicture = student.ProfilePicture;
            StudentProfilePictureContentType = student.ProfilePictureContentType;

            // Get enrolled courses
            var currentQuarterDate = QuarterHelper.QuarterDates()
                .FirstOrDefault(qd => QuarterHelper.GetQuarterFromDate(DateTime.Today) == Enum.Parse<Quarter>(qd.Name));
            if (currentQuarterDate != null)
            {
                CurrentQuarterName = currentQuarterDate.Name;
                CurrentQuarterYear = currentQuarterDate.StartDate.Year;
            }

            var allEnrolledCourses = await _context.Courses
                .Include(c => c.Teacher)
                .Where(c => c.Enrollments.Any(e => e.StudentId == studentId))
                .ToListAsync();

            EnrolledCourses = allEnrolledCourses
                .Where(c => QuarterHelper.GetQuarterFromDate(c.StartDate) == QuarterHelper.GetQuarterFromDate(DateTime.Today))
                .ToList();

            // Get current teachers
            CurrentTeachers = EnrolledCourses
                .Select(c => c.Teacher)
                .Where(t => t != null)
                .Distinct()
                .ToList()!;

            // Get course grades using GradeCalculator
            foreach (var course in EnrolledCourses)
            {
                var assignments = await _context.Assignments
                    .Include(a => a.AssignmentScores)
                    .Where(a => a.CourseId == course.Id)
                    .ToListAsync();

                var (earned, possible) = GradeCalculator.CalculateStudentGrade(studentId, assignments);
                CourseGrades[course.Id] = GradeCalculator.GetLetterGrade(earned, possible);
                CourseNames[course.Id] = course.Name;
            }

            // Get assignments for each course
            foreach (var course in EnrolledCourses)
            {
                var assignments = await _context.Assignments
                    .Where(a => a.CourseId == course.Id)
                    .ToListAsync();

                var assignmentInfos = new List<AssignmentInfo>();
                foreach (var a in assignments)
                {
                    var ag = await _context.AssignmentScores
                        .FirstOrDefaultAsync(g => g.AssignmentId == a.Id && g.StudentId == studentId);
                    int pointsEarned = ag?.PointsEarned ?? 0;
                    int pointsPossible = a.PointsPossible;
                    string grade = GradeCalculator.GetLetterGrade(pointsEarned, pointsPossible);

                    assignmentInfos.Add(new AssignmentInfo
                    {
                        Title = a.Title,
                        DueDate = a.DueDate,
                        PointsPossible = pointsPossible,
                        PointsEarned = pointsEarned,
                        Grade = grade
                    });
                }
                AssignmentsByCourse[course.Id] = assignmentInfos;
            }

            return Page();
        }

        public async Task<IActionResult> OnPostUploadProfilePictureAsync(int studentId, IFormFile ProfilePicture)
        {
            var student = await _context.Students.FindAsync(studentId);
            if (student == null)
                return NotFound();

            if (ProfilePicture != null && ProfilePicture.Length > 0)
            {
                using (var ms = new MemoryStream())
                {
                    await ProfilePicture.CopyToAsync(ms);
                    student.ProfilePicture = ms.ToArray();
                    student.ProfilePictureContentType = ProfilePicture.ContentType;
                }
                await _context.SaveChangesAsync();
            }

            return RedirectToPage(new { studentId });
        }
    }
}

WebApplication1/Pages/Students/Create.cshtml
@page
@model WebApplication1.Pages.Students.CreateModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Student</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Student.FirstName" class="control-label"></label>
                <input asp-for="Student.FirstName" class="form-control" />
                <span asp-validation-for="Student.FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Student.LastName" class="control-label"></label>
                <input asp-for="Student.LastName" class="form-control" />
                <span asp-validation-for="Student.LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Student.DateOfBirth" class="control-label"></label>
                <input asp-for="Student.DateOfBirth" class="form-control" />
                <span asp-validation-for="Student.DateOfBirth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Student.Email" class="control-label"></label>
                <input asp-for="Student.Email" class="form-control" />
                <span asp-validation-for="Student.Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Student.StreetAddress" class="control-label"></label>
                <input asp-for="Student.StreetAddress" class="form-control" />
                <span asp-validation-for="Student.StreetAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Student.City" class="control-label"></label>
                <input asp-for="Student.City" class="form-control" />
                <span asp-validation-for="Student.City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Student.State" class="control-label"></label>
                <input asp-for="Student.State" class="form-control" />
                <span asp-validation-for="Student.State" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Student.PostalCode" class="control-label"></label>
                <input asp-for="Student.PostalCode" class="form-control" />
                <span asp-validation-for="Student.PostalCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Student.Country" class="control-label"></label>
                <input asp-for="Student.Country" class="form-control" />
                <span asp-validation-for="Student.Country" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Student.MobilePhone" class="control-label"></label>
                <input asp-for="Student.MobilePhone" class="form-control" />
                <span asp-validation-for="Student.MobilePhone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Student.HomePhone" class="control-label"></label>
                <input asp-for="Student.HomePhone" class="form-control" />
                <span asp-validation-for="Student.HomePhone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Student.EmergencyContactName" class="control-label"></label>
                <input asp-for="Student.EmergencyContactName" class="form-control" />
                <span asp-validation-for="Student.EmergencyContactName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Student.EmergencyContactPhone" class="control-label"></label>
                <input asp-for="Student.EmergencyContactPhone" class="form-control" />
                <span asp-validation-for="Student.EmergencyContactPhone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplication1/Pages/Students/Dashboard.cshtml
@page "/Students/Dashboard/{studentId:int}"
@model WebApplication1.Pages.Students.DashboardModel

@{
    ViewData["Title"] = "Student Dashboard";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h1>Student Dashboard - @Model.StudentFirstName</h1>

<div class="alert alert-info mt-3">
    <strong>Enrollment for next quarter is available now!</strong>
    <a class="btn btn-primary btn-sm ms-2" asp-page="./Enroll/Enroll" asp-route-id="@Model.StudentId">Go to Enrollment</a>
</div>

<div class="row">
    <div class="col-md-3 mb-4 text-center">
        <h4>Profile Picture</h4>
        @if (Model.StudentProfilePicture != null && Model.StudentProfilePictureContentType != null)
        {
            var base64 = Convert.ToBase64String(Model.StudentProfilePicture);
            <img src="data:@Model.StudentProfilePictureContentType;base64,@base64" alt="Profile Picture" style="max-width:150px;max-height:150px;border-radius:50%;" />
        }
        else
        {
            <span>No profile picture uploaded.</span>
        }
        <br />
        <a href="#" class="mt-2 d-inline-block" data-bs-toggle="modal" data-bs-target="#uploadProfilePictureModal">
            Change Picture
        </a>
    </div>
</div>

<!-- Modal for uploading profile picture -->
<div class="modal fade" id="uploadProfilePictureModal" tabindex="-1" aria-labelledby="uploadProfilePictureModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="uploadProfilePictureModalLabel">Upload Profile Picture</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form method="post" enctype="multipart/form-data" asp-page-handler="UploadProfilePicture" asp-route-studentId="@Model.StudentId">
            <div class="form-group">
                <input type="file" name="ProfilePicture" class="form-control" accept="image/*" />
            </div>
            <button type="submit" class="btn btn-primary mt-2">Upload</button>
        </form>
      </div>
    </div>
  </div>
</div>

<h2>Enrolled Courses</h2>
<h5>@Model.CurrentQuarterName @Model.CurrentQuarterYear</h5>
<table class="table">
    <thead>
        <tr>
            <th>Course Name</th>
            <th>Teacher</th>
            <th>Grade</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    @foreach (var course in Model.EnrolledCourses)
    {
        var grade = Model.CourseGrades.ContainsKey(course.Id) ? Model.CourseGrades[course.Id] : null;
        <tr>
            <td>
                @course.Name
            </td>
            <td>@course.Teacher?.LastName</td>
            <td>@(grade != null ? grade.ToString() : "-")</td>
            <td>
                <button class="btn btn-link" onclick="showAssignments(@course.Id)">View Assignments</button>
            </td>
        </tr>
    }
    </tbody>
</table>

<!-- Modal for assignments -->
<div class="modal fade" id="assignmentsModal" tabindex="-1" aria-labelledby="assignmentsModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="assignmentsModalLabel">Assignments for <span id="modalCourseTitle"></span></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <table class="table" id="modalAssignmentsTable">
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Due Date</th>
                    <th>Points Possible</th>
                    <th>Grade</th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<h2>Current Teachers</h2>
<table class="table">
    <thead>
        <tr>
            <th>Teacher Name</th>
            <th>Email</th>
        </tr>
    </thead>
    <tbody>
    @foreach (var teacher in Model.CurrentTeachers)
    {
        <tr>
            <td>@teacher.FirstName @teacher.LastName</td>
            <td>@teacher.Email</td>
        </tr>
    }
    </tbody>
</table>

@section Scripts {
    <script>
        var assignmentsData = @Html.Raw(Newtonsoft.Json.JsonConvert.SerializeObject(Model.AssignmentsByCourse));
        var courseNames = @Html.Raw(Newtonsoft.Json.JsonConvert.SerializeObject(Model.CourseNames));

        function showAssignments(courseId) {
            var tableBody = document.getElementById('modalAssignmentsTable').getElementsByTagName('tbody')[0];
            var courseTitle = document.getElementById('modalCourseTitle');
            tableBody.innerHTML = '';
            courseTitle.textContent = courseNames[courseId] || '';
            if (assignmentsData[courseId] && assignmentsData[courseId].length > 0) {
                assignmentsData[courseId].forEach(function (a) {
                    var row = document.createElement('tr');
                    row.innerHTML = `<td>${a.Title}</td>
                                     <td>${a.DueDate ? a.DueDate.substring(0,10) : ''}</td>
                                     <td>${a.PointsEarned} / ${a.PointsPossible}</td>
                                     <td>${a.Grade}</td>`;
                    tableBody.appendChild(row);
                });
            } else {
                var row = document.createElement('tr');
                row.innerHTML = `<td colspan="4" class="text-center">No assignments for this course.</td>`;
                tableBody.appendChild(row);
            }
            var modal = new bootstrap.Modal(document.getElementById('assignmentsModal'));
            modal.show();
        }
    </script>
}

WebApplication1/Pages/Students/Delete.cshtml
@page
@model WebApplication1.Pages.Students.DeleteModel

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Student</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Student.FirstName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Student.FirstName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Student.LastName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Student.LastName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Student.DateOfBirth)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Student.DateOfBirth)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Student.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Student.Email)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="Student.Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>